### ISSUE TITLE
[1.9] Crashes dedicated server during gameplay

### ISSUE THREAD

**Issue by kreezxil** [elix-x/Avoid-Exploding-Creepers#3]
Crash Report: https://gist.github.com/4e4ef8bb2e08b02c8b403d5c4a38d42d

**Comment by Elix-x** [comment]
First time seeing this. If you relog into world, does it crash again or work? Is it first time that this happens?

**Comment by kreezxil** [comment]
it's been happening, this was the first time we pinpointed it. Most likely
started when I started using Forge builds higher than build 1900

**Comment by Elix-x** [comment]
Ok. I'll update forge and check.
